import Head from "next/head";
import Navbar from "../components/Navbar";

import HomeSection from "../components/sections/HomeSection";
import ProfileSection from "../components/sections/ProfileSection";
import ProjectSection from "../components/sections/ProjectSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HomeSection />
      <ProfileSection />
      <ProjectSection />
    </>
  );
}
