import Head from "next/head";
import { Box } from "@chakra-ui/react";

import Navbar from "../Navbar";

export default function Layout({ children }) {
  return (
    <Box as="main">
      <Head>
        <title>Joshua Dela Cruz | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
    </Box>
  );
}
