import { motion } from "framer-motion";
import Head from "next/head";
import { Box } from "@chakra-ui/react";

import Navbar from "@components/Navbar";
import Footer from "@components/Footer";

const variants = {
  hidden: { opacity: 0, x: 0, y: 20 },
  enter: { opacity: 1, x: 0, y: 0 },
  exit: { opacity: 0, x: -0, y: 20 },
};

export default function Layout({ children }) {
  return (
    <motion.div
      variants={variants}
      initial="hidden"
      animate="enter"
      exit="exit"
    >
      <Head>
        <title>Joshua Dela Cruz | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Box as="main">{children}</Box>
      <Footer />
    </motion.div>
  );
}
