import Head from "next/head";
import { Box } from "@chakra-ui/react";

import Navbar from "../Navbar";
import Footer from "../footer";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Joshua Dela Cruz | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Box as="main" px={5} py={10}>
        {children}
      </Box>
      <Footer />
    </>
  );
}
